title: Ryan Snodgrass
logo: /assets/img/solarglasses.jpg
  #/assets/img/IMG_20171115_144337279c.jpg
  #/assets/img/logo.png
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
