title: Ryan Snodgrass
logo: /assets/img/solarglasses.png
description: Ryan Snodgrass, mechanical engineer at Cornell University.
show_downloads: false
google_analytics: UA-125829271-1
theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
